import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lymeng Naret",
};

const NUM_DOTS = 96; // Number of dots used in CircularBorder
const DELAY_INCREMENT = 0.1; // Seconds per dot
const ANGLE_PER_DOT = 360 / NUM_DOTS; // Degrees per dot
export const CIRCULAR_PROPS = {
  NUM_DOTS,
  DELAY_INCREMENT,
  ANGLE_PER_DOT,
};

export const HOME_PROPS = {
  FULL_NAME: "Lymeng Naret",
  ONE_LINER:
    "I develop full-stack in my spare time & focus on test automation, manual, and reliability at work.",
  PERSONAL_DESCRIPTIONS: `I am a developer who enjoys full-stack as I get to see the code I write come to life (or occasionally break live). I graduated from UBC's Computer Science in May 2024 and am currently working as a Software Developer in Test at Safe Software.

    My most enjoyable experience in software development has been working in an agile group. Working alone under pressure to deliver my tasks timely and then collaborating with the team to achieve a shared goal truly fuels my passion for software development. While planning is essential, I often find the real understanding comes when I dive into the process. I enjoy—and even prefer—the challenges and struggles if it means building something meaningful.

    In my free time, I enjoy gaming, basketball, and working out. I am breaking out of my comfort, one zone at a time. 
    `,
};

export const PROJECTS = [
  {
    id: 0,
    title: "Yojana",
    timeline: "Jan 2023 - Apr 2023",
    display: true,
    tech: [
      "TypeScript",
      "React",
      "NextJS",
      "MySQL",
      "Prisma",
      "TailwindCSS",
      "NextAuth",
      "Azure Active Directory",
    ],
    description: `Cloud-based Calendar built from scratch. Features a view that fits an entire year's events within a single page/view with instant CRUD operations. Supports server-side rendering, authentication, and cross-platform compatibility. An 8-member agile group. 
      `,
    url: "https://github.com/CPSC319-2022/Yojana",
    summary: `A cloud-based enterprise calendar built from scratch for managing key company dates with admin and user modules for Associated Engineering.
      Supports instant CRUD operations with server-side rendering for fast performance. Includes secure user authentication and integrates with external calendar systems like iCal and Outlook
      - Replaced company's paper calendar through a unique cloud-based enterprise calendar.
      - Oversaw frontend including: creating mockup with figma and helped with 80% of all UI components.
      - Assisted with backend APIs and integration with MySQL. Fixed complex time zone bugs to improve performance by over 100%. 
      - Written unit tests and end-to-end automated regression testing with Cypress and GitHub action.
      `,
  },
  {
    id: 1,
    title: "TravelersTea",
    timeline: "May 2023 - Aug 2023",
    display: true,
    tech: [
      "JavaScript",
      "MongoDB",
      "Express",
      "React",
      "NodeJS",
      "Docker",
      "Mapbox API",
      "Google Places API",
      "OpenAI API",
    ],
    description: `A Full-Stack Trip-Generating MERN Application. Generates tailored travel itineraries based on user preferences. Features an interactive map with autogenerated pinned locations. A 5-member agile group.
      `,
    url: "https://travelerstea-906d.onrender.com/",
    summary: `A Trip Planning App that tailors travel itineraries based on user preferences and providing detailed information about destinations.
      -	Led project architecture, CI/CD pipeline with Docker & GitHub Action, enhancing productivity in an agile team of 5.
      -	Used Redux Toolkit to manage global states with reducers & slices, and employed Thunks to handle asynchronous actions for fetching, updating, and managing actions’ life cycles.
      -	Implemented index caching system and data compression to improve API performance speed by 49%.
      `,
  },

  {
    id: 2,
    title: "AgroBot",
    timeline: "Nov 2022 - Oct 2023",
    display: true,
    tech: ["Python", "OpenCV", "Tkinter", "Performance/Manual Testing"],
    description: `Navigation Software for Agricultural Robots. Write and optimize navigation algorithms to integrate into robot. Implemented video frame processing algorithms. Developed performance tests for real-time robot navigation.
      `,
    url: "https://github.com/UBCAgroBot/Navigation",
    summary: `Software for autonomous agricultural robots that processes video frames for navigation.
      -	Utilized OpenCV & NumPy to enhance a navigation algorithm for real-time video frame object tracking, optimizing the robot’s path-finding capabilities.
      -	Developed performance tests for all existing algorithm with Python, ensuring smooth performance on mock field.
      -	Integrated the navigation algorithm and UI with ROS 2 and Arduino, achieving autonomous navigation on a Jetson board to successfully navigate a mock field.
    `,
  },
  {
    id: 3,
    title: "Inventory Management System",
    timeline: "2021",
    display: false,
    tech: [],
    description: `My First Full-Stack MERN Application Features item addition, deletion, and display in a carousel for easy navigation. Includes a custom modal dialog for item details, search, and sorting. Integrated Express server for secure user authentication.
      `,
    url: "",
    summary: `An Inventory Management System built using the MERN stack. 
      - Supports item addition, deletion, and detailed display with a custom dialog/modal. 
      - Implemented search and sorting capabilities for efficient inventory management. 
      - Secure user authentication is handled by an Express server.
      `,
  },
  {
    id: 4,
    title: "Database Projects",
    timeline: "2021",
    display: false,
    tech: [],
    description: `Interactive SQL-Based Database. Astronomical Entities Wikipedia. A custom SQL-based interactive database with REST APIs.
      `,
    url: "",
    summary: `Interactive SQL-Based Database Project
      - An interactive SQL-based database with custom APIs for efficient data query.
      - A Wikipedia-like application for astronomical entities featuring a searchable database.
      `,
  },
  {
    id: 5,
    title: "API Query Language",
    timeline: "Jan 2024 - Apr 2024",
    display: true,
    tech: ["Java", "OOP", "DSL", "Java Swing", "JUnit"],
    description: `A Domain Specific Language for Interacting with web APIs. Streamlines the process of making API requests, handling responses, and implementing logic based on those responses. Provides a straightforward, readable syntax.
      `,
    url: "",
    summary: `AQL (API Query Language) aims to help with common frustrations encountered when interacting with web APIs.
      - Designed and wrote all algorithms and objects from scratch.
      -	Formulated ANTLR4 lexer and grammar for a DSL to simplify web-API interactions for developers.
      -	Modularized and wrote unit tests, regression tests, and end-to-end tests with 100% line-coverage using JUnit.
      -	Built a console UI with syntax highlight, coding area, and output terminal using Java Swing.
      `,
  },
  {
    id: 6,
    title: "LiveTranslator",
    timeline: "Sep 2023 - Dec 2023",
    display: true,
    tech: ["Python", "Pytesseract", "Multi-threading"],
    description: `A Software that translate video frames and overlay on screen. Utilized Pytesseract OCR for text recognition. Designed frame processors for efficient translation.
      `,
    url: "https://github.com/NLmeng/LiveTranslator",
    summary: `LiveTranslator finds and translates texts from frames/images within the region or window using OCR and overlays the translated texts.
      -	Engineered an application with user-friendly interface, leveraging multi-threading for efficient performance.
      -	Designed frame processors and utilized Pytesseract OCR, achieving a 100% improvement in accuracy.
      `,
  },
  {
    id: 7,
    title: "Portfolio Websites",
    timeline: "Ongoing",
    display: true,
    tech: ["TypeScript", "NextJS", "React", "S3", "DynamoDB", "Sentry"],
    description: `A portfolio website to showcase my projects and skills. Developed and deployed a full-stack interactive portfolio. Incorporated scalable storage solutions with S3 & DynamoDB’s NoSQL database and Sentry for error monitoring.
      `,
    url: "https://lymengblog.vercel.app/",
    summary: `I occasionally work on my portfolio website to showcase my projects and skills.
      -	Developed and deployed a full-stack interactive portfolio.
      -	Incorporated scalable storage solutions with S3 & DynamoDB’s NoSQL database and Sentry for error monitoring.
      `,
  },
  {
    id: 8,
    title: "Maze Solver",
    timeline: "2021 - 2022",
    display: true,
    tech: ["Java", "Design Patterns", "Algorithm Designs"],
    description: `A Pathfinding Algorithm Project. Utilized the A* algorithm with optimized heuristics for faster pathfinding. Fully interactive board with hint and solve features. Real-time performance optimizations.
      `,
    url: "https://github.com/NLmeng/maze-solver",
    summary: `A Pathfinding Algorithm Project
      - Implemented an A* algorithm with custom heuristics for enhanced speed. 
      - Features a fully interactive board allowing users to visualize and solve mazes. 
      - Includes real-time hints and solving capabilities.
      `,
  },
];

export const EXPERIENCE_DATA = [
  {
    year: "2020",
    title: "First Post-Secondary Education",
    subtitle: "UBC CS'24",
    description: `My Bachelor’s degree, majoring in Computer Science at the University of British Columbia was from 2020 to 2024.

      My first programming language was C++, which I explored through Harvard's CS50 course during high school. Later, I started my first project in Java and quickly became intrigued by backend development.
      Some of my most relevant courses include: Software Engineering Project, Applied Industry Practices, Advanced Software Engineering, Algorithm Design and Analysis, and Advanced Relational Databases.
     
      I am interested in software engineering and have a peculiar interest in data and databases. In my third year, I developed a passion for frontend development, which later evolved into a love for full-stack development. During this time, I collaborated with like-minded peers and found great enjoyment in group projects. 
      
      By the end of my Bachelor's in 2024, I achieved the Dean’s Honour Roll, received the Trek Excellence Award, made lasting friendships, and graduated with high distinction.
      `,
  },
  {
    year: "2021",
    title: "GitHub Side Projects",
    subtitle: "GitHub Side Projects",
    description: `Amidst COVID, I turned to GitHub to explore side projects. 
      Fully remote classes gave me a lot of time to explore. Many ideas were inspired by what I learnt from school and it was my own way to practice what I learnt.

      Key Projects:
      - Maze Solver: A pathfinding algorithm project utilizing the A* algorithm and data structures with optimized heuristics for faster pathfinding. It features a fully interactive board with hint and solve functionalities for better visualization.
      - Inventory Management System: My first full-stack MERN application, featuring item addition, deletion, and a carousel for easy navigation. It also included a custom modal dialog for item details, search, and sorting.
      - Data Query App: Developed interactive queries via REST APIs and a Wikipedia-like application for astronomical entities using MySQL and React. 
      `,
  },
  {
    year: "2022",
    title: "Year 3",
    subtitle: "SDE @ UBC AgroBot",
    description: `As school returned to in-person, I began exploring more opportunities to code, including via school clubs.

      I pursued my first hands-on experience as a volunteer Software Developer Engineer at UBC AgroBot, dedicating approximately 20 hours a week. I worked both independently and collaboratively within a small subgroup of 6 developers.
      I learned Python to enhance a navigation algorithm for real-time video frame object tracking, optimizing the robot’s pathfinding capabilities. Additionally, I developed performance tests for all existing algorithms, ensuring smooth operation in mock field environments.

      I contributed from November 2022 to October 2023. I helped conclude the project by integrating navigation algorithms and UI with ROS 2 and Arduino, achieving autonomous navigation on a Jetson board to successfully traverse a mock field.
      `,
  },
  {
    year: "2023",
    title: "Continue Learning",
    subtitle: "Agile Group Projcts",
    description: `In 2023, I had the opportunity to immerse myself in agile group projects, where I honed my full-stack development skills and learned to effectively collaborate within diverse teams. 
    
      One of my favorite achievements was the development of Yojana, a cloud-based enterprise calendar built from scratch with a unique view that fits a year's events into a single page. Working alongside a team of eight, we designed and implemented a comprehensive system capable of managing key company dates with both admin and user modules. I took an active role in the frontend, creating mockups with Figma and developing ~80% of the UI components, while also assisting with backend API development and integration with MySQL. The experience deepened my understanding of server-side rendering, authentication, and end-to-end testing, solidifying my passion for building scalable, user-friendly applications.

      Following this, I led the development of TravelersTea, a trip-planning application designed to tailor itineraries based on user preferences. In a team of five, I designed the CI/CD pipeline using Docker and GitHub Actions, enabling seamless deployments. I implemented Redux Toolkit for global state management and optimized API performance by introducing an index caching system, resulting in a 49% speed improvement. The application featured an interactive map with autogenerated pinned locations, making it an intuitive and visually engaging tool for travelers. 
      `,
  },
  {
    year: "2024",
    title: "Volunteers & Full-Time",
    subtitle: "SDET @ Safe Software",
    description: `This year marked a pivotal year in my career as I transitioned from volunteering to a full-time role in software development. 
    
      From May to July, I volunteered at Blockchain Venture Capital. I explored the blockchain technology and contributed to enhancing its ecosystem. I conducted research and participated in brainstorming sessions aimed at improving the startup’s blockchain platform.

      Starting September, I joined Safe Software as a Software Developer in Test. Currently, with my manager's help, I'm solely responsible for the triage and debugging of over 10,000 JUnit tests for the server. Going Beyond, I am developing automated testing frameworks such as API testsdi using Postman and Cypress to streamline testing processes. 
      `,
  },
];

export const TEXT_SIZE = {
  MAIN_HEADER: "text-4xl md:text-5xl",
  MAIN_BODY: "text-sm md:text-md",
  HEADER: "text-2xl md:text-3xl",
  BODY: "text-xs md:text-sm",
  MINI: "text-[10px] md:text-[12px]",
};
